CREATE TABLE universities (
index INT,
Name VARCHAR(60) NOT NULL,
Location VARCHAR(65) NOT NULL,
Rank_USNewsWorldReport INT NOT NULL,
Description VARCHAR NOT NULL,
TuitionFees Money NOT NULL,
InState Money,
Undergrad_Enrollment VARCHAR(65) NOT NULL,
description2 VARCHAR,
Rank_2022 INT,
state_code VARCHAR(2),
studentPopulation INT,
campusSetting VARCHAR(65),
medianBaseSalary INT,
longitude DEC,
latitude DEC,
website VARCHAR(60),
phoneNumber VARCHAR(20),
city VARCHAR(65),
country VARCHAR (65),
state VARCHAR(65),
region VARCHAR(65),
yearFounded INT,
stateCode VARCHAR(2),
collegeType VARCHAR(45),
carnegieClassification VARCHAR(60),
studentFacultyRatio INT,
totalStudentPop INT,
undergradPop INT,
totalGrantAid INT,
percentOfStudentsFinAid INT,
percentOfStudentsGrant INT
);

SELECT * FROM universities;